---
# Playbook for  Hadoop slave servers

- name: Set JAVA_HOME in hadoop service
  lineinfile:
    regexp="# export JAVA_HOME=/usr/lib/j2sdk1.6-sun"
    line="export JAVA_HOME=/usr/lib/jvm/java-8-oracle/jre/"
    dest=/etc/hadoop/conf/hadoop-env.sh
    state=present

- name: Copy avro jars
  copy: src={{item}} dest=/usr/lib/hadoop-0.20/ owner=root group=root
  with_items:
  - avro-1.7.6.jar
  - avro-mapred-1.7.6-hadoop1.jar

- name: Copy the hadoop configuration files for non ha
  template: src=roles/common/templates/hadoop_conf/{{item}}.j2 dest=/etc/hadoop/conf/{{item}}
  with_items: 
   - core-site.xml
   - hadoop-metrics.properties
   - hadoop-metrics2.properties
   - hdfs-site.xml
   - log4j.properties
   - mapred-site.xml
   - slaves
   - ssl-client.xml.example
   - ssl-server.xml.example
  notify: restart hadoop slave services

- name: Create the data directory for the slave nodes to store the data
  file: path={{ item }} owner=hdfs group=hdfs state=directory
  with_items: hadoop.dfs_datanode_data_dir
  when: install_hdfs

- name: Create the data directory for the slave nodes for mapreduce
  file: path={{ item }} owner=mapred group=mapred state=directory
  with_items: hadoop.mapred_local_dir

- name: start hadoop tasktracker services
  service: name=hadoop-0.20-tasktracker state=started

- name: start hadoop datanode services
  service: name=hadoop-0.20-datanode state=started
  when: install_hdfs
