---
# The main playbook to deploy the site

- hosts: hadoopmaster
  roles:
   - common
   - java

- hosts: hadoopslave1
  roles:
   - common
   - java

- hosts: hadoopslave2
  roles:
   - common
   - java

- hosts: hadoop_masters
  roles:
  - { role: hadoop_primary }

- hosts: hadoop_slaves
  roles:
  - { role: hadoop_slaves }

