---
- name: Add the Cloudera Repository
  apt_repository: repo="deb http://archive.cloudera.com/debian maverick-cdh3 contrib" state=present

- name: Add the Cloudera src Repository
  apt_repository: repo="deb-src http://archive.cloudera.com/debian maverick-cdh3 contrib" state=present

- name: Add the Cloudera APT repository key
  apt_key: data="{{ lookup('file', 'cloudera-repo.key') }}" state=present

- name: Install the tasktracker packages
  apt: name=hadoop-0.20-tasktracker state=installed

- name: Install the datanode packages
  apt: name=hadoop-0.20-datanode state=installed

- name: Install the tasktracker packages
  apt: name=hadoop-0.20-jobtracker state=installed

- name: Install the datanode packages
  apt: name=hadoop-0.20-namenode state=installed

- name: Install vim
  apt: name=vim state=installed
