---
# Playbook for  Hadoop master servers

- name: Set JAVA_HOME in hadoop service
  lineinfile:
    regexp="# export JAVA_HOME=/usr/lib/j2sdk1.6-sun"
    line="export JAVA_HOME=/usr/lib/jvm/java-8-oracle/jre/"
    dest=/etc/hadoop/conf/hadoop-env.sh
    state=present

- name: Copy the hadoop configuration files for no ha
  template: src=roles/common/templates/hadoop_conf/{{ item }}.j2 dest=/etc/hadoop/conf/{{ item }} mode=644
  with_items: 
   - core-site.xml
   - hadoop-metrics.properties
   - hadoop-metrics2.properties
   - hdfs-site.xml
   - log4j.properties
   - mapred-site.xml
   - slaves
   - ssl-client.xml.example
   - ssl-server.xml.example
  notify: restart hadoop master services

- name: Create the data directory for the namenode metadata
  file: path=hadoop.dfs_namenode_name_dir owner=hdfs group=hdfs state=directory

- name: Format the namenode
  shell: creates=/usr/lib/hadoop/namenode.formatted su - hdfs -c "hadoop namenode -format" && touch /usr/lib/hadoop/namenode.formatted

- name: create namedir work folder
  shell: mkdir /namedir1 
  ignore_errors: yes

- name: assign permission on namedir work folder
  shell: sudo chown hdfs:hdfs /namedir1
  ignore_errors: yes

- name: start hadoop namenode services
  service: name=hadoop-0.20-namenode state=started

- name: Give permissions for mapred users
  shell: creates=/usr/lib/hadoop/namenode.initialized su - hdfs -c "hadoop fs -chown hdfs:hadoop /"; su - hdfs -c "hadoop fs -chmod 0775 /" && touch /usr/lib/hadoop/namenode.initialized

- name: create mapred work folder
  shell: mkdir /mapred1 
  ignore_errors: yes

- name: assign permission on mapred work folder
  shell: sudo chown mapred:mapred /mapred1
  ignore_errors: yes

- name: start hadoop jobtracker services
  service: name=hadoop-0.20-jobtracker state=started
