---
- include: webupd8.yml

- name: Update repositories cache
  apt:
    update_cache: yes

- name: Install the jdk
  apt:
    name: oracle-java8-installer
    state: present

- name: set jdk as default
  apt:
    name: oracle-java8-set-default
    state: present
